[package]
name = "source"
description = "alternative to rust iterators"
version = "0.2.0"
authors = ["Sönke Hahn <soenkehahn@gmail.com>"]
edition = "2018"
license = "BSD-3-Clause"

[dependencies]
utf8-chars = "^0.1"
